openapi: 3.0.0
info:
  title: Insight Queries
  version: IQ 1.0
  description: >-
    This page contains the essential endpoints of the InfoSum API that help users securely analysize data via insight queries, allowing the user to plan and provide insights based on data. You can download the swagger file above or email solutions@infosum.com to share a Postman Collection.


    InfoSum Support: support@infosum.com | [Terms of Service](https://www.infosum.com/legals/website-terms) | [Official Documentation](https://support.infosum.com/)


    description to be added


    Task List 


    1. Create a insight query


    2. Optional: Check if query ran successfully


    3. Get results of query

    <h3>Parameter Reference Table</h3>
    <table border="1" style="border-collapse: collapse; width: 100%;">
      <tr style="background-color: #f2f2f2;">
        <th style="padding: 8px; text-align: center; border: 3px solid #ddd;">Step Number</th>
        <th style="padding: 8px; text-align: center; border: 3px solid #ddd;">Parameter Name</th>
        <th style="padding: 8px; text-align: center; border: 3px solid #ddd;">Parameter Structure</th>
        <th style="padding: 8px; text-align: center; border: 3px solid #ddd;">Where to find it</th>
        <th style="padding: 8px; text-align: center; border: 3px solid #ddd;">When to collect</th>
      </tr>
      <tr>
        <td style="padding: 8px; border: 1px solid #ddd;">1</td>
        <td style="padding: 8px; border: 1px solid #ddd;">Query</td>
        <td style="padding: 8px; border: 1px solid #ddd;">"SELECT self.ID FROM self INTERSECT them"</td>
        <td style="padding: 8px; border: 1px solid #ddd;">Write it in <strong>Query Tool</strong></td>
        <td style="padding: 8px; border: 1px solid #ddd;">Have ready before hand. Please not the quotes are not optional.</td>
      </tr>
      <tr>
        <td style="padding: 8px; border: 1px solid #ddd;">2, 3</td>
        <td style="padding: 8px; border: 1px solid #ddd;">Query ID</td>
        <td style="padding: 8px; border: 1px solid #ddd;">xx</td>
        <td style="padding: 8px; border: 1px solid #ddd;">Response from step 1</td>
        <td style="padding: 8px; border: 1px solid #ddd;">Can be grabbed from output of step 1</td>
      </tr>
    </table>

    
    Add some example queries of each function!
    COUNT()
    TOPN(field, n)
    AGGREGATE(field1)
    AGGREGATE(field1, field2)
    SUM(field) + avg *add note on privacy budget
    
    WHERE statments


servers:
  - url: http://{{baseurl}}
  - url: https://api.infosum.com
components:
  securitySchemes:
    apikeyAuth:
      type: http
      scheme: apikey
security:
  - apikeyAuth: []
tags:
  - name: Insight Queries
paths:
  /api/v1/activations:
    post:
      tags:
        - Insight Queries
      summary: 1. Create a Query
      description: >-
        Queue a Query for execution. Returns immediately with an ID of the Query
        created.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                query: Query
                campaign_name: Campaign Name
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                query_id: <string>
                done: <boolean>
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
                metadata:
                  quis57: <string>
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
                metadata:
                  quis57: <string>
        '500':
          description: Internal Server Error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                code: <integer>
                message: <string>
                details:
                  - '@type': <string>
                    incididunt_6: {}
                  - '@type': <string>
  /api/v1/activations/{query_id}:
    get:
      tags:
        - Insight Queries
      summary: 2. Get a Result
      description: Get the Result of a Query, when it is available.
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: query_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                dimensions:
                  - value: <string>
                    category: <string>
                    count: <long>
                    continuous: <boolean>
                    private_id: <string>
                    dimensions:
                      - value: >-
                          <Circular reference to
                          #/components/schemas/tyraelDimension detected>
                      - value: >-
                          <Circular reference to
                          #/components/schemas/tyraelDimension detected>
                  - value: <string>
                    category: <string>
                    count: <long>
                    continuous: <boolean>
                    private_id: <string>
                    dimensions:
                      - value: >-
                          <Circular reference to
                          #/components/schemas/tyraelDimension detected>
                      - value: >-
                          <Circular reference to
                          #/components/schemas/tyraelDimension detected>
                audience: <long>
                quality_measures:
                  redaction_threshold_outlier: <float>
                  rounding_threshold_outlier: <float>
                  model_accuracy: <float>
                  result_precision_include_empty_bins: <float>
                  result_precision_exclude_empty_bins: <float>
                join_metadata:
                  - from_dataset:
                      id: <string>
                      name: <string>
                    to_dataset:
                      id: <string>
                      name: <string>
                    keys:
                      - key_id: <int64>
                        name: <string>
                      - key_id: <int64>
                        name: <string>
                  - from_dataset:
                      id: <string>
                      name: <string>
                    to_dataset:
                      id: <string>
                      name: <string>
                    keys:
                      - key_id: <int64>
                        name: <string>
                      - key_id: <int64>
                        name: <string>
                count_metadata:
                  - dataset:
                      id: <string>
                      name: <string>
                    keys:
                      - key_id: <int64>
                        name: <string>
                      - key_id: <int64>
                        name: <string>
                  - dataset:
                      id: <string>
                      name: <string>
                    keys:
                      - key_id: <int64>
                        name: <string>
                      - key_id: <int64>
                        name: <string>
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
                metadata:
                  quis57: <string>
        '404':
          description: Not Found
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                message: <string>
                metadata:
                  quis57: <string>
        '500':
          description: Internal Server Error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                code: <integer>
                message: <string>
                details:
                  - '@type': <string>
                    incididunt_6: {}
                  - '@type': <string>
  /api/v2/destinations/instances/{destination_id}:
    get:
      tags:
        - Insight Queries
      summary: 3. Get Destination Instance
      description: Returns details about an owned Destination Instance.
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: destination_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                destination:
                  config: {}
                  created_time: <dateTime>
                  creator_id: <string>
                  description: <string>
                  destination_type_id: <string>
                  editable_paths:
                    - <string>
                    - <string>
                  id: <string>
                  incoming_share_id: <string>
                  name: <string>
                  outgoing_share_ids:
                    - <string>
                    - <string>
                  owner_id: <string>
                  permission_ids:
                    - <string>
                    - <string>
                  permissioned_to_permitted_company: <boolean>
                  updated_time: <dateTime>
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                details:
                  code: <string>
                  message: <string>
                error:
                  code: <string>
                  message: <string>
                help_url: <string>
                request_id: <string>
                time: <dateTime>
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                details:
                  code: <string>
                  message: <string>
                error:
                  code: <string>
                  message: <string>
                help_url: <string>
                request_id: <string>
                time: <dateTime>
        '403':
          description: Forbidden
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                details:
                  code: <string>
                  message: <string>
                error:
                  code: <string>
                  message: <string>
                help_url: <string>
                request_id: <string>
                time: <dateTime>
        '404':
          description: Not Found
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                details:
                  code: <string>
                  message: <string>
                error:
                  code: <string>
                  message: <string>
                help_url: <string>
                request_id: <string>
                time: <dateTime>
        '500':
          description: Internal Server Error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: Internal Server Error
                  value:
                    details:
                      code: <string>
                      message: <string>
                    error:
                      code: <string>
                      message: <string>
                    help_url: <string>
                    request_id: <string>
                    time: <dateTime>
                example-1:
                  summary: An unexpected error response.
                  value:
                    details:
                      code: <string>
                      message: <string>
                    error:
                      code: <string>
                      message: <string>
                    help_url: <string>
                    request_id: <string>
                    time: <dateTime>